site_name: Citrix Receiver for Linux 13.9.1 Command-line Reference
site_description: Citrix Receiver for Linux 13.9.1 Command-line Reference
theme_dir: citrix-sdk
markdown_extensions:
  - admonition
  - codehilite
  - toc:
     anchorlink: True

pages:
- Index: index.md
